#!/usr/bin/env python3
"""Generate fixed Butano action-definition tables from ROM-bound JSON banks."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


COST_NAMES = {
    0: "none",
    1: "current_chakra",
    2: "current_hp",
    3: "no_scalar_resource_special",
    5: "battle_local_ninja_tool_slot",
}

TARGET_NAMES = {
    0: "self_or_implicit_actor",
    1: "friendly_unit_policy_1",
    2: "opponent_unit",
    3: "occupied_unit",
    4: "empty_tile",
    5: "friendly_unit_policy_5",
}


def _active_row(index: int, raw: bytes) -> dict[str, int]:
    return {
        "id": index,
        "cost_kind": raw[0],
        "scalar_cost": int.from_bytes(raw[10:12], "little"),
        "tool_slot": 0xFF,
        "animation_family": raw[1],
        "effect_code": raw[2] & 0x3F,
        "effect_flags": raw[2] & 0xC0,
        "potency": raw[4],
        "base_hit_count": raw[5],
        "success_rate_percent": raw[6],
        "duration_turns": raw[9],
        "target_policy": raw[3] & 0x07,
        "target_flags": raw[3] & 0xF8,
        "distance_and_line_flags": raw[7],
        "area_range_and_shape_flags": raw[8],
        "upgrade_target_type": raw[12],
        "per_level_growth": int.from_bytes(raw[14:16], "little"),
    }


def _tool_row(index: int, raw: bytes) -> dict[str, int]:
    return {
        "id": index,
        "cost_kind": 5,
        "scalar_cost": 0,
        "tool_slot": 0xFF,
        "animation_family": raw[0],
        "effect_code": raw[2] & 0x3F,
        "effect_flags": raw[2] & 0xC0,
        "potency": raw[4],
        "base_hit_count": raw[5],
        "success_rate_percent": raw[6],
        "duration_turns": raw[9],
        "target_policy": raw[3] & 0x07,
        "target_flags": raw[3] & 0xF8,
        "distance_and_line_flags": raw[7],
        "area_range_and_shape_flags": raw[8],
        "upgrade_target_type": 7,
        "per_level_growth": 0,
    }


def _load_rows(path: Path, expected_count: int) -> list[bytes]:
    bank = json.loads(path.read_text(encoding="utf-8"))
    if bank.get("entry_count") != expected_count or len(bank.get("entries", [])) != expected_count:
        raise ValueError(f"{path} must contain exactly {expected_count} entries")
    rows = []
    for index, entry in enumerate(bank["entries"]):
        raw = bytes.fromhex(entry["raw_hex"])
        if len(raw) != 16:
            raise ValueError(f"{path} row {index} is not 16 bytes")
        rows.append(raw)
    return rows


def load_action_content(root: Path | str) -> dict[str, list[dict[str, int]]]:
    root = Path(root)
    active_rows = _load_rows(root / "sequel/content/battle-config/bank.json", 87)
    tool_rows = _load_rows(root / "sequel/content/skills/bank.json", 94)
    active_actions = [_active_row(index, raw) for index, raw in enumerate(active_rows)]
    ninja_tools = [_tool_row(index, raw) for index, raw in enumerate(tool_rows)]
    for identity, rows in (("active action", active_actions), ("ninja tool", ninja_tools)):
        for row in rows:
            if row["cost_kind"] not in COST_NAMES:
                raise ValueError(f"{identity} {row['id']} has unknown cost kind")
            if row["target_policy"] not in TARGET_NAMES:
                raise ValueError(f"{identity} {row['id']} has unknown target policy")
    return {"active_actions": active_actions, "ninja_tools": ninja_tools}


def _cpp_row(row: dict[str, int]) -> str:
    cost = COST_NAMES[row["cost_kind"]]
    target = TARGET_NAMES[row["target_policy"]]
    return (
        "    action_definition{ "
        f"{row['id']}, "
        f"cost_policy{{ action_cost_kind::{cost}, {row['scalar_cost']}, {row['tool_slot']} }}, "
        f"presentation_binding{{ {row['animation_family']} }}, "
        "effect_descriptor{ "
        f"{row['effect_code']}, {row['effect_flags']}, {row['potency']}, "
        f"{row['base_hit_count']}, {row['success_rate_percent']}, {row['duration_turns']} "
        "}, "
        f"target_policy{{ target_policy_kind::{target}, {row['target_flags']} }}, "
        f"range_shape{{ {row['distance_and_line_flags']}, {row['area_range_and_shape_flags']} }}, "
        f"upgrade_rule{{ {row['upgrade_target_type']}, {row['per_level_growth']} }} "
        "},"
    )


def generate_header(root: Path | str) -> str:
    content = load_action_content(root)
    active = "\n".join(_cpp_row(row) for row in content["active_actions"])
    tools = "\n".join(_cpp_row(row) for row in content["ninja_tools"])
    return f"""// Generated by tools/generate_butano_battle_action_content.py. Do not edit.
#ifndef KONOHA_GENERATED_BATTLE_ACTION_CONTENT_H
#define KONOHA_GENERATED_BATTLE_ACTION_CONTENT_H

#include \"konoha/battle_action_system.h\"

#include <array>

namespace konoha
{{

inline constexpr std::array<action_definition, 87> active_action_definitions = {{{{
{active}
}}}};

inline constexpr std::array<action_definition, 94> ninja_tool_action_definitions = {{{{
{tools}
}}}};

[[nodiscard]] constexpr action_definition ninja_tool_action_for_slot(
        ninja_tool_id id, std::uint8_t slot)
{{
    action_definition result = ninja_tool_action_definitions[id];
    result.cost.tool_slot = slot;
    return result;
}}

}}

#endif
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("butano-sequel/game/include/konoha/generated_battle_action_content.h"),
    )
    args = parser.parse_args()
    header = generate_header(args.root)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header, encoding="utf-8")
    print(f"generated {args.output} with 87 active actions and 94 ninja tools")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
