#!/usr/bin/env python3
"""Generate fixed Butano character definitions from the ROM-bound unit bank."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def _slot(source: dict) -> dict[str, int]:
    return {
        "action_id": source["id"],
        "initial_state": source["initial_state"],
        "unlock_level": source["unlock_level"],
        "reserved": source["reserved"],
    }


def load_unit_content(root: Path | str) -> list[dict]:
    root = Path(root)
    bank = json.loads((root / "sequel/content/units/bank.json").read_text(encoding="utf-8"))
    if bank.get("entry_count") != 63 or len(bank.get("entries", [])) != 63:
        raise ValueError("unit bank must contain exactly 63 records")
    result = []
    for index, entry in enumerate(bank["entries"]):
        if entry["character_id"] != index:
            raise ValueError(f"unit row {index} has mismatched character_id")
        primary = [_slot(slot) for slot in entry["primary_slots"]]
        secondary = [_slot(slot) for slot in entry["secondary_slots"]]
        if len(primary) != 15 or len(secondary) != 24:
            raise ValueError(f"unit row {index} has invalid action-slot counts")
        result.append(
            {
                "character_id": index,
                "active": bool(entry["active"]),
                "attack": entry["template_02_base"],
                "defense": entry["template_03_base"],
                "agility": entry["template_04_base"],
                "movement": entry["template_05_base"],
                "ninja_tool_capacity": entry["template_06_base"],
                "chakra_capacity": entry["template_08_base"],
                "hand_seals": entry["template_0a_base"],
                "max_hp": entry["template_0e_base"],
                "primary_slots": primary,
                "secondary_slots": secondary,
            }
        )
    return result


def _cpp_slot(slot: dict[str, int]) -> str:
    return (
        "action_slot_definition{ "
        f"{slot['action_id']}, {slot['initial_state']}, "
        f"{slot['unlock_level']}, {slot['reserved']} "
        "}"
    )


def _cpp_slots(slots: list[dict[str, int]], count: int) -> str:
    values = ", ".join(_cpp_slot(slot) for slot in slots)
    return f"std::array<action_slot_definition, {count}>{{{{ {values} }}}}"


def _cpp_unit(unit: dict) -> str:
    primary = _cpp_slots(unit["primary_slots"], 15)
    secondary = _cpp_slots(unit["secondary_slots"], 24)
    active = "true" if unit["active"] else "false"
    return (
        "    unit_definition{ "
        f"{unit['character_id']}, {active}, {unit['attack']}, {unit['defense']}, "
        f"{unit['agility']}, {unit['movement']}, {unit['ninja_tool_capacity']}, "
        f"{unit['chakra_capacity']}, {unit['hand_seals']}, {unit['max_hp']}, "
        f"{primary}, {secondary} "
        "},"
    )


def generate_header(root: Path | str) -> str:
    units = load_unit_content(root)
    rows = "\n".join(_cpp_unit(unit) for unit in units)
    return f"""// Generated by tools/generate_butano_battle_unit_content.py. Do not edit.
#ifndef KONOHA_GENERATED_BATTLE_UNIT_CONTENT_H
#define KONOHA_GENERATED_BATTLE_UNIT_CONTENT_H

#include \"konoha/battle_unit_content.h\"

#include <array>

namespace konoha
{{

inline constexpr std::array<unit_definition, 63> unit_definitions = {{{{
{rows}
}}}};

}}

#endif
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("butano-sequel/game/include/konoha/generated_battle_unit_content.h"),
    )
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate_header(args.root), encoding="utf-8")
    print(f"generated {args.output} with 63 unit definitions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
